# Generated by Django 5.2.5 on 2025-10-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Padel Tips & Training', 'Padel Tips & Training'), ('Venues & Facilities', 'Venues & Facilities'), ('Community & Players', 'Community & Players'), ('Tournaments & Events', 'Tournaments & Events'), ('News & Industry Updates', 'News & Industry Updates'), ('Lifestyle & Wellness', 'Lifestyle & Wellness')], default='Padel Tips & Training', max_length=50),
        ),
    ]
