# Generated by Django 5.2.7 on 2025-10-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_venue_max_price_remove_venue_min_price_and_more'),
        ('main', '0010_alter_article_category'),
    ]

    operations = [
    ]
