# Generated by Django 5.2.7 on 2025-10-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20251024_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_url_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_url_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_url_5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='price_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
