# Generated by Django 5.2.5 on 2025-10-24 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0011_merge_20251024_1544'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='image_url_2',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='image_url_3',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='image_url_4',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='image_url_5',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='price_range',
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
